language: python
python:
  - "3.8"
cache: pip
services: mongodb
env:
  - BACKEND_TEST_DIR=backend
# move to backend, install dependencies, and run test suite
script:
  - cd $BACKEND_TEST_DIR && pip install -r requirements.txt && pytest