version: "3.8"
services:
  frontend:
    tty: true
    stdin_open: true
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    env_file:
    - ./backend/.env
    ports:
      - 5000:5000