version: "3.8"
services:
  backend:
    build: ./backend
    volumes: 
      - ./backend:/backend
    env_file:
    - ./backend/.env
    ports:
      - 5000:5000

  frontend:
    tty: true
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: